openapi: 3.1.0
info:
  title: Plataforma GALA API
  version: 0.1.0
  description: >
    Plataforma GALA (Generación Audiovisual Local con Avatares).
    Contrato API v0 (local, sin auth). Upload de assets en v0 es simple (multipart).
servers:
  - url: http://localhost:8080
    description: Local

tags:
  - name: Health
  - name: Assets
  - name: Models
  - name: Templates
  - name: Jobs

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  service: { type: string }
                  version: { type: string }
                required: [status, service, version]

  /assets:
    post:
      tags: [Assets]
      summary: Upload asset (v0 simple multipart upload)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                kind:
                  type: string
                  description: Asset kind
                  enum: [source_video, avatar_input, music, render_output, thumbnail, overlay, background]
                label:
                  type: string
              required: [file, kind]
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

  /assets/{assetId}:
    get:
      tags: [Assets]
      summary: Get asset metadata
      parameters:
        - $ref: "#/components/parameters/assetId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      tags: [Assets]
      summary: Delete asset
      parameters:
        - $ref: "#/components/parameters/assetId"
      responses:
        "204":
          description: Deleted
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

  /assets/{assetId}/url:
    get:
      tags: [Assets]
      summary: Get asset download URL (local proxy URL in v0)
      parameters:
        - $ref: "#/components/parameters/assetId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetURLResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /assets/{assetId}/content:
    get:
      tags: [Assets]
      summary: Stream asset binary content
      parameters:
        - $ref: "#/components/parameters/assetId"
      responses:
        "200":
          description: Binary stream
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /models:
    post:
      tags: [Models]
      summary: Create model (avatar profile)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateModelRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

    get:
      tags: [Models]
      summary: List models
      parameters:
        - in: query
          name: q
          schema: { type: string }
          description: Search by name/tag
        - in: query
          name: tag
          schema: { type: string }
          description: Filter by tag
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelsListResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /models/{modelId}:
    get:
      tags: [Models]
      summary: Get model
      parameters:
        - $ref: "#/components/parameters/modelId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    patch:
      tags: [Models]
      summary: Update model (partial)
      parameters:
        - $ref: "#/components/parameters/modelId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateModelRequest"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      tags: [Models]
      summary: Delete model
      parameters:
        - $ref: "#/components/parameters/modelId"
      responses:
        "204":
          description: Deleted
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

  /templates:
    post:
      tags: [Templates]
      summary: Create template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTemplateRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

    get:
      tags: [Templates]
      summary: List templates
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplatesListResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /templates/{templateId}:
    get:
      tags: [Templates]
      summary: Get template
      parameters:
        - $ref: "#/components/parameters/templateId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    patch:
      tags: [Templates]
      summary: Update template (partial)
      parameters:
        - $ref: "#/components/parameters/templateId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTemplateRequest"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      tags: [Templates]
      summary: Delete template
      parameters:
        - $ref: "#/components/parameters/templateId"
      responses:
        "204":
          description: Deleted
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

  /jobs:
    post:
      tags: [Jobs]
      summary: Create render job (batch)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateJobRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobResponse"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalError"

    get:
      tags: [Jobs]
      summary: List jobs
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [QUEUED, RUNNING, DONE, FAILED]
        - in: query
          name: template_id
          schema: { type: string }
        - in: query
          name: model_id
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobsListResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /jobs/{jobId}:
    get:
      tags: [Jobs]
      summary: Get job details (including outputs if DONE)
      parameters:
        - $ref: "#/components/parameters/jobId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobDetailResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /jobs/{jobId}/cancel:
    post:
      tags: [Jobs]
      summary: Cancel job (v0 optional)
      parameters:
        - $ref: "#/components/parameters/jobId"
      responses:
        "200":
          description: Cancelled/Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobResponse"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  parameters:
    assetId:
      name: assetId
      in: path
      required: true
      schema: { type: string }
    modelId:
      name: modelId
      in: path
      required: true
      schema: { type: string }
    templateId:
      name: templateId
      in: path
      required: true
      schema: { type: string }
    jobId:
      name: jobId
      in: path
      required: true
      schema: { type: string }

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorEnvelope"
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorEnvelope"
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorEnvelope"
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorEnvelope"

  schemas:
    ErrorEnvelope:
      type: object
      properties:
        error:
          type: object
          properties:
            code: { type: string }
            message: { type: string }
            details:
              type: object
              additionalProperties: true
          required: [code, message]
      required: [error]

    Asset:
      type: object
      properties:
        id: { type: string }
        kind:
          type: string
          enum: [source_video, avatar_input, music, render_output, thumbnail, overlay, background]
        provider:
          type: string
          enum: [localfs]
        object_key: { type: string }
        mime: { type: string }
        size_bytes: { type: integer }
        checksum: { type: string }
        label: { type: string }
        created_at: { type: string, format: date-time }
      required: [id, kind, provider, object_key, mime, size_bytes, created_at]

    AssetResponse:
      type: object
      properties:
        asset:
          $ref: "#/components/schemas/Asset"
      required: [asset]

    AssetURLResponse:
      type: object
      properties:
        asset_id: { type: string }
        url: { type: string }
        expires_at: { type: string, format: date-time }
      required: [asset_id, url]

    Model:
      type: object
      properties:
        id: { type: string }
        stage_name: { type: string }
        tags:
          type: array
          items: { type: string }
        preset:
          type: object
          additionalProperties: true
        asset_ids:
          type: array
          items: { type: string }
        created_at: { type: string, format: date-time }
      required: [id, stage_name, created_at]

    CreateModelRequest:
      type: object
      properties:
        stage_name: { type: string }
        tags:
          type: array
          items: { type: string }
        preset:
          type: object
          additionalProperties: true
        asset_ids:
          type: array
          items: { type: string }
      required: [stage_name]

    UpdateModelRequest:
      type: object
      properties:
        stage_name: { type: string }
        tags:
          type: array
          items: { type: string }
        preset:
          type: object
          additionalProperties: true
        asset_ids:
          type: array
          items: { type: string }

    ModelResponse:
      type: object
      properties:
        model:
          $ref: "#/components/schemas/Model"
      required: [model]

    ModelsListResponse:
      type: object
      properties:
        models:
          type: array
          items:
            $ref: "#/components/schemas/Model"
      required: [models]

    TemplateFormat:
      type: object
      properties:
        width: { type: integer }
        height: { type: integer }
        fps: { type: integer }
      required: [width, height, fps]

    Template:
      type: object
      properties:
        id: { type: string }
        type: { type: string }
        name: { type: string }
        duration_ms: { type: integer }
        format:
          $ref: "#/components/schemas/TemplateFormat"
        params_schema:
          type: object
          additionalProperties: true
        defaults:
          type: object
          additionalProperties: true
        created_at: { type: string, format: date-time }
      required: [id, type, name, created_at]

    CreateTemplateRequest:
      type: object
      properties:
        type: { type: string }
        name: { type: string }
        duration_ms: { type: integer }
        format:
          $ref: "#/components/schemas/TemplateFormat"
        params_schema:
          type: object
          additionalProperties: true
        defaults:
          type: object
          additionalProperties: true
      required: [type, name]

    UpdateTemplateRequest:
      type: object
      properties:
        type: { type: string }
        name: { type: string }
        duration_ms: { type: integer }
        format:
          $ref: "#/components/schemas/TemplateFormat"
        params_schema:
          type: object
          additionalProperties: true
        defaults:
          type: object
          additionalProperties: true

    TemplateResponse:
      type: object
      properties:
        template:
          $ref: "#/components/schemas/Template"
      required: [template]

    TemplatesListResponse:
      type: object
      properties:
        templates:
          type: array
          items:
            $ref: "#/components/schemas/Template"
      required: [templates]

    JobLog:
      type: object
      properties:
        ts: { type: string, format: date-time }
        level: { type: string }
        msg: { type: string }
      required: [ts, level, msg]

    JobOutput:
      type: object
      properties:
        variant: { type: integer }
        video_asset_id: { type: string }
        thumbnail_asset_id: { type: string }
        captions_asset_id: { type: string }
      required: [variant, video_asset_id]

    Job:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        status:
          type: string
          enum: [QUEUED, RUNNING, DONE, FAILED]
        template_id: { type: string }
        model_ids:
          type: array
          items: { type: string }
        params:
          type: object
          additionalProperties: true
        created_at: { type: string, format: date-time }
        started_at: { type: string, format: date-time }
        finished_at: { type: string, format: date-time }
      required: [id, status, template_id, created_at]

    CreateJobRequest:
      type: object
      properties:
        name: { type: string }
        template_id: { type: string }
        model_ids:
          type: array
          items: { type: string }
        inputs:
          type: object
          additionalProperties: true
        params:
          type: object
          additionalProperties: true
        output:
          type: object
          additionalProperties: true
        batch:
          type: object
          properties:
            count: { type: integer, minimum: 1 }
            variants:
              type: array
              items:
                type: object
                additionalProperties: true
          additionalProperties: true
      required: [template_id, model_ids]

    JobResponse:
      type: object
      properties:
        job:
          $ref: "#/components/schemas/Job"
      required: [job]

    JobsListResponse:
      type: object
      properties:
        jobs:
          type: array
          items:
            $ref: "#/components/schemas/Job"
      required: [jobs]

    JobDetail:
      allOf:
        - $ref: "#/components/schemas/Job"
        - type: object
          properties:
            outputs:
              type: array
              items:
                $ref: "#/components/schemas/JobOutput"
            logs:
              type: array
              items:
                $ref: "#/components/schemas/JobLog"

    JobDetailResponse:
      type: object
      properties:
        job:
          $ref: "#/components/schemas/JobDetail"
      required: [job]
