openapi: 3.1.0
info:
  title: Plataforma GALA API
  version: 0.1.0
  description: >
    Plataforma GALA (Generación Audiovisual Local con Avatares).
    Contrato API v0 (local, sin auth).

servers:
  - url: http://localhost:8080
    description: Local

tags:
  - name: Health
  - name: Assets
  - name: Models
  - name: Templates
  - name: Jobs

paths:
  $ref: "./paths/index.yaml"

components:
  parameters:
    $ref: "./parameters.yaml"
  responses:
    $ref: "./responses.yaml"
  schemas:
    $ref: "./schemas/index.yaml"
